# Generated by Django 2.2.1 on 2019-09-25 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbv_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='age',
            field=models.PositiveIntegerField(default=4),
            preserve_default=False,
        ),
    ]
